#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(BATON_PASS) \
    F(ENCORE) \
    F(FACADE) \
    F(FAKE_OUT) \
    F(PROTECT) \
    F(RAPID_SPIN) \
    F(RECOVER) \
    F(RETURN) \
    F(SWORDS_DANCE) \
    F(WISH) \
    F(FIRE_BLAST) \
    F(FLAMETHROWER) \
    F(FLAME_CHARGE) \
    F(FLARE_BLITZ) \
    F(OVERHEAT) \
    F(SUNNY_DAY) \
    F(WILL_O_WISP) \
    F(AQUA_JET) \
    F(FLIP_TURN) \
    F(LIQUIDATION) \
    F(SCALD) \
    F(SURF) \
    F(RAIN_DANCE) \
    F(WAVE_CRASH) \
    F(ENERGY_BALL) \
    F(GIGA_DRAIN) \
    F(GRASS_KNOT) \
    F(TRAILBLAZE) \
    F(CHARGE_BEAM) \
    F(ELECTROWEB) \
    F(THUNDERBOLT) \
    F(THUNDER_WAVE) \
    F(VOLT_SWITCH) \
    F(BLIZZARD) \
    F(ICE_BEAM) \
    F(ICE_SPINNER) \
    F(ICY_WIND) \
    F(SNOWSCAPE) \
    F(AURA_SPHERE) \
    F(BODY_PRESS) \
    F(BRICK_BREAK) \
    F(BULK_UP) \
    F(CLOSE_COMBAT) \
    F(DETECT) \
    F(DRAIN_PUNCH) \
    F(FOCUS_BLAST) \
    F(SUPERPOWER) \
    F(GUNK_SHOT) \
    F(SLUDGE_BOMB) \
    F(TOXIC) \
    F(TOXIC_SPIKES) \
    F(BULLDOZE) \
    F(EARTHQUAKE) \
    F(EARTH_POWER) \
    F(HIGH_HORSEPOWER) \
    F(SPIKES) \
    F(ACROBATICS) \
    F(BRAVE_BIRD) \
    F(DEFOG) \
    F(ROOST) \
    F(TAILWIND) \
    F(CALM_MIND) \
    F(LIGHT_SCREEN) \
    F(PSYCHIC) \
    F(PSYCHIC_FANGS) \
    F(PSYCHIC_NOISE) \
    F(REFLECT) \
    F(REST) \
    F(TRICK_ROOM) \
    F(BUG_BUZZ) \
    F(LEECH_LIFE) \
    F(STICKY_WEB) \
    F(QUIVER_DANCE) \
    F(U_TURN) \
    F(POWER_GEM) \
    F(ROCK_SLIDE) \
    F(SANDSTORM) \
    F(STEALTH_ROCK) \
    F(STONE_EDGE) \
    F(POLTERGEIST) \
    F(SHADOW_BALL) \
    F(DRACO_METEOR) \
    F(DRAGON_CLAW) \
    F(DRAGON_DANCE) \
    F(DRAGON_PULSE) \
    F(SCALE_SHOT) \
    F(DARK_PULSE) \
    F(FOUL_PLAY) \
    F(KNOCK_OFF) \
    F(NASTY_PLOT) \
    F(SUCKER_PUNCH) \
    F(TAUNT) \
    F(FLASH_CANNON) \
    F(HEAVY_SLAM) \
    F(IRON_HEAD) \
    F(ALLURING_VOICE) \
    F(DAZZLING_GLEAM) \
    F(MOONBLAST) \
    F(MOONLIGHT) \
    F(PLAY_ROUGH)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
